ignore:
  - "ext/amdgpu_preconditioner.jl"
  - "ext/amdgpu_wrapper.jl"
  - "ext/ExaPFAMDGPUExt.jl"
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
